default:
  image: alpine:latest

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/lesspass-client/${CI_COMMIT_TAG}"
  ARTIFACTS: lesspass-client-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}-linux-amd64
  PACKAGE_NAME: lesspass-client-${CI_COMMIT_TAG}-linux-amd64.tar.xz
  PACKAGE_PATH: lesspass-client-${CI_COMMIT_TAG}-linux-amd64

stages:
  - Test
  - Build
  - Package
  - Publish
  - Release

Test lesspass-client:
  stage: Test
  image: rust:buster
  script:
    - cargo test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target

Build lesspass-client:
  stage: Build
  image: rust:buster
  script:
    - cargo build --release --locked
  artifacts:
    name: ${ARTIFACTS}
    paths:
      - target/release/lesspass-client
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target

Package lesspass-client:
  stage: Package
  script:
    - install -Dm755 "target/release/lesspass-client" "${ARTIFACTS}/lesspass-client"
    - install -Dm644 "README.md" "${ARTIFACTS}/README.md"
    - install -Dm644 "LICENSE" "${ARTIFACTS}/LICENSE"
  artifacts:
    name: ${ARTIFACTS}
    paths:
      - ${ARTIFACTS}/
  rules:
    - if: $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"

Package lesspass-client release:
  stage: Package
  script:
    - apk -U --no-progress add xz
    - install -Dm755 "target/release/lesspass-client" "${PACKAGE_PATH}/lesspass-client"
    - install -Dm644 "README.md" "${PACKAGE_PATH}/README.md"
    - install -Dm644 "LICENSE" "${PACKAGE_PATH}/LICENSE"
    - tar cvJf "${PACKAGE_NAME}" "${PACKAGE_PATH}"
  artifacts:
    name: ${ARTIFACTS}
    paths:
      - ${PACKAGE_NAME}
  rules:
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ID == "43285042"

Publish lesspass-client release:
  stage: Publish
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${PACKAGE_NAME} "${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"
  rules:
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ID == "43285042"

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: |
    release-cli create --name "Release ${CI_COMMIT_TAG}" --tag-name ${CI_COMMIT_TAG} \
      --assets-link "{\"name\":\"${PACKAGE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}\"}"
  rules:
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ID == "43285042"
